<?

// Design master list
$designList = array(
	array(
			"001",
			"tranquille",
			"Dave Shea",
			"http://www.mezzoblue.com/",
	),
	array(
			"002",
			"Salmon Cream Cheese",
			"Dave Shea"	,
			"http://www.mezzoblue.com/",
	),
	array(
			"003",
			"Stormweather",
			"Dave Shea",
			"http://www.mezzoblue.com/",
	),
	array(
			"004",
			"arch4.20",
			"Dave Shea",
			"http://www.mezzoblue.com/",
	),
	array(
			"005",
			"Blood Lust",
			"Dave Shea",
			"http://www.mezzoblue.com/",
	),
	array(
			"006",
			"Wicked Grove",
			"D. Keith Robinson",
			"http://www.dkeithrobinson.com/",
	),
	array(
			"007",
			"deep thoughts",
			"Jason Estes",
			"#",
	),
	array(
			"008",
			"RPM",
			"Bruno Cunha",
			"#",
	),
	array(
			"009",
			"Dead or Alive",
			"Michael Pick",
			"http://www.mikepick.com/",
	),
	array(
			"010",
			"A Garden Apart",
			"Dan Cederholm",
			"http://www.simplebits.com/",
	),
	array(
			"011",
			"meliorism",
			"Brett J. Gilbert",
			"#",
	),
	array(
			"012",
			"TechnOhm",
			"Josh Ambrutis",
			"#",
	),
	array(
			"013",
			"Coastal Breeze",
			"Dave Shea",
			"http://www.mezzoblue.com/",
	),
	array(
			"014",
			"Samuraai",
			"Minz Meyer",
			"http://www.minzweb.de/",
	),
	array(
			"015",
			"Boddhidarma",
			"Michael Angeles",
			"http://www.urlgreyhot.com/",
	),
	array(
			"016",
			"The Garden Beneath",
			"Minz Meyer",
			"http://www.minzweb.de/",
	),
	array(
			"017",
			"Golden Mean",
			"Douglas Bowman",
			"http://www.stopdesign.com/",
	),
	array(
			"018",
			"Wrapped in Burlap",
			"John Simons",
			"http://www.royalbarrel.com/",
	),
	array(
			"019",
			"What Lies Beneath",
			"Michael Pick",
			"http://www.mikepick.com/",
	),
	array(
			"020",
			"Friendly Beaches",
			"Sophie G",
			"http://www.sophie-g.net/",
	),
	array(
			"021",
			"Calm &amp; Smooth",
			"Cornelia Lange",
			"http://www.clkm.de/",
	),
	array(
			"022",
			"viridity",
			"Laura MacArthur",
			"#",
	),
	array(
			"023",
			"fleur de l&#8217;avant-garde",
			"Michael Switzer",
			"#",
	),
	array(
			"024",
			"Not So Minimal",
			"Dan Rubin",
			"http://www.superfluousbanter.org/",
	),
	array(
			"025",
			"mnemonic",
			"Dave Shea",
			"http://www.mezzoblue.com/",
	),
	array(
			"026",
			"Zunflower",
			"Radu Darvas",
			"http://www.cssgatto.com/",
	),
	array(
			"027",
			"Gothica",
			"Patrick H. Lauke",
			"http://www.splintered.co.uk/",
	),
	array(
			"028",
			"Atlantis",
			"Kevin Davis",
			"http://alazanto.org/",
	),
	array(
			"029",
			"Backyard",
			"Ray Henry",
			"http://www.reh3.com/",
	),
	array(
			"030",
			"Entomology",
			"Jon Hicks",
			"http://exp.hicksdesign.co.uk/",
	),
	array(
			"031",
			"Hedges",
			"Kev Mears",
			"http://www.mearso.com/",
	),
	array(
			"032",
			"Crab Apple",
			"Jai Brinkofski",
			"#",
	),
	array(
			"033",
			"Fleur-de-lys",
			"Claire Campbell",
			"#",
	),
	array(
			"034",
			"zengrounds",
			"Andrea Piernock",
			"http://www.snooble.com/",
	),
	array(
			"035",
			"Release One",
			"Didier Hilhorst",
			"http://www.nundroo.com/",
	),
	array(
			"036",
			"White Lily",
			"Jens Kristensen",
			"http://j-k.com/",
	),
	array(
			"037",
			"pr&#234;t-&#225;-porter",
			"Minz Meyer",
			"http://www.minzweb.de/",
	),
	array(
			"038",
			"Creepy Crawly",
			"Luke Redpath",
			"",
	),
	array(
			"039",
			"Erratic Blue",
			"Ian Main",
			"#",
	),
	array(
			"040",
			"The Question Why",
			"Diane Clayton",
			"http://www.schisma.net/",
	),
	array(
			"041",
			"door to my garden",
			"Patrick H. Lauke",
			"http://www.splintered.co.uk/",
	),
	array(
			"042",
			"Stone Washed",
			"Andrew Hayward",
			"http://www.mooncalf.me.uk/",
	),
	array(
			"043",
			"Burning",
			"Kevin &#038; Ethel Davis",
			"#",
	),
	array(
			"044",
			"si6",
			"Shaun Inman",
			"http://www.shauninman.com/",
	),
	array(
			"045",
			"I Dream in Colour",
			"Jeff Bilen",
			"http://www.scribblersclub.com/",
	),
	array(
			"046",
			"sub:lime",
			"Andy Budd",
			"http://www.andybudd.com/",
	),
	array(
			"047",
			"dusk",
			"Jon Hicks",
			"http://exp.hicksdesign.co.uk/",
	),	
	array(
			"048",
			"HoriZental",
			"Cl&#233;ment &#8216;fastclemmy&#8217; Hardouin",
			"http://www.fastclemmy.com/",
	),	
	array(
			"049",
			"Buddha",
			"Daniel Leroux",
			"#",
	),	
	array(
			"050",
			"First Summary",
			"Cornelia Lange",
			"http://www.clkm.de/",
	),	
	array(
			"051",
			"Commercial Drive",
			"Wendy Foster",
			"#",
	),	
	array(
			"052",
			"Postage Paid",
			"Mike Stenhouse",
			"http://www.donotremove.co.uk/",
	),
	array(
			"053",
			"Self-Growth",
			"Ray Henry",
			"http://www.reh3.com/",
	),
	array(
			"054",
			"Gecko&#8217;s Eye",
			"Sandra Greco",
			"http://www.magritte.it/",
	),
	array(
			"055",
			"zenlightenment",
			"Lance Leonard",
			"http://www.solarfrog.com/",
	),
	array(
			"056",
			"Elevation",
			"Nigel Goodfellow",
			"http://www.beforethedog.com/",
	),
	array(
			"057",
			"This is Cereal",
			"Shaun Inman",
			"http://www.shauninman.com/",
	),
	array(
			"058",
			"Radio Zen",
			"Marc LA van den Heuvel",
			"http://www.mlavdh.nl/",
	),
	array(
			"059",
			"Dune Temple",
			"Greg Reimer",
			"http://www.drpeterjones.com/",
	),
	array(
			"060",
			"Extreme Limits",
			"Richard Chatfield",
			"#",
	),
	array(
			"061",
			"Sky",
			"Stefan Petre",
			"http://www.eyecon.ro/",
	),
	array(
			"062",
			"Gemination",
			"Egor Kloos",
			"http://www.dutchcelt.nl/",
	),
	array(
			"063",
			"Elastic Lawn",
			"Patrick Grifiths",
			"http://htmldog.com/ptg/",
	),
	array(
			"064",
			"Night Drive",
			"Dave Shea",
			"http://www.mezzoblue.com/",
	),
	array(
			"065",
			"New Groove",
			"Martin Neumann",
			"http://www.rushmedia.de/",
	),
	array(
			"066",
			"Focus &amp; Shoot",
			"Colectivo YTW",
			"#",
	),
	array(
			"067",
			"A Silent Strength",
			"Ray Henry",
			"http://www.reh3.com/",
	),
	array(
			"068",
			"Ballade",
			"Charlotte Lambert",
			"#",
	),
	array(
			"069",
			"Bonsai Sky",
			"Mike Davidson",
			"http://www.mikeindustries.com/",
	),
	array(
			"070",
			"CS(S) Monk",
			"Cedric Savarese",
			"http://www.4213miles.com/",
	),
	array(
			"071",
			"Garden Party",
			"Bobby van der Sluis",
			"http://www.bobbyvandersluis.com/",
	),
	array(
			"072",
			"Outburst",
			"Chris Vincent",
			"#",
	),
	array(
			"073",
			"Emmakade",
			"Alexander Christiaan Jacob (ACJ)",
			"http://acjs.net/",
	),
	array(
			"074",
			"Egyptian Dawn",
			"James Abbott",
			"mailto:jambot@hotmail.com",
	),
	array(
			"075",
			"Lost HighWay",
			"Julien Roumagnac",
			"http://www.j-roumagnac.net/",
	),
	array(
			"076",
			"Lotus",
			"Chika",
			"http://deja.boo.jp/japdsn/",
	),
	array(
			"077",
			"Hop",
			"Guillaume Lahalle",
			"#",
	),
	array(
			"078",
			"Muto Verde",
			"Alex Taylor",
			"#",
	),
	array(
			"079",
			"Green Tea",
			"Amy Rae Som",
			"http://www.avisualmind.com/",
	),
	array(
			"080",
			"Zen Pool",
			"Clinton Barth",
			"http://www.516media.com/",
	),
	array(
			"081",
			"seashore",
			"Clinton Barth",
			"http://www.sightdesign.de/",
	),
	array(
			"082",
			"Miracle Cure",
			"Joseph Pearson",
			"http://www.make-believe.org/",
	),
	array(
			"083",
			"Springtime",
			"Bo&eacute;r Attila",
			"http://www.calcium.ro/",
	),
	array(
			"084",
			"Start Listening!",
			"Liz Lubowitz",
			"#",
	),
	array(
			"085",
			"Oceans Apart",
			"Ryan Sims",
			"http://www.justwatchthesky.com/",
	),
	array(
			"086",
			"RedFrog",
			"Bernd Willenberg",
			"http://www.willenberg.biz/",
	),
	array(
			"087",
			"Maya",
			"Bernd Willenberg",
			"http://www.willenberg.biz/",
	),
	array(
			"088",
			"Tulipe",
			"Eric Shepherd",
			"http://www.arkitrave.com/",
	),
	array(
			"089",
			"Dark Industrial",
			"Ray Henry",
			"http://www.reh3.com/",
	),
	array(
			"090",
			"Open Window",
			"Ray Henry",
			"http://www.reh3.com/",
	),
	array(
			"091",
			"webZine",
			"Vincent Valentin",
			"#",
	),
	array(
			"092",
			"Port of Call",
			"Jessica Dunn",
			"http://vcdesignconcept.com/",
	),
	array(
			"093",
			"South of the Border",
			"Rob Shields",
			"http://www.dotcat.org/",
	),
	array(
			"094",
			"Deco",
			"Marc Trudel",
			"http://www.marctrudel.com/",
	),
	array(
			"095",
			"Corporate ZenWorks",
			"Derek Hansen",
			"http://www.dejoha.com/",
	),
	array(
			"096",
			"Japanese Garden",
			"Masanori Kawachi",
			"http://www.jugglinglife.org/",
	),
	array(
			"097",
			"No Frontiers!",
			"Michal Mokrzycki",
			"#",
	),
	array(
			"098",
			"Edo and Tokyo",
			"Daisuke Sato",
			"http://www.coutworks.com/",
	),
	array(
			"099",
			"Wiggles the Wonderworm",
			"Joseph Pearson",
			"http://www.make-believe.org/",
	),
	array(
			"100",
			"15 Petals",
			"Eric Meyer &amp; Dave Shea",
			"http://www.meyerweb.com/",
	),
	array(
			"101",
			"Punkass",
			"Mikhel Proulx",
			"",
	),
	array(
			"102",
			"Revolution!",
			"David Hellsing",
			"",
	),
	array(
			"103",
			"Odyssey",
			"Terrence Conley",
			"http://www.liquidarch.com/",
	),
	array(
			"104",
			"Invitation",
			"Brad Daily",
			"http://www.bradleyboy.com/",
	),
	array(
			"105",
			"Austrian&#8217;s Darker Side",
			"Rene Grassegger",
			"#",
	),
	array(
			"106",
			"Mediterranean",
			"John Whittet",
			"http://www.basseq.com/",
	),
	array(
			"107",
			"Defiance",
			"James Ehly",
			"http://www.ehlydesign.com/",
	),

	// 108 removed for copyright violation
	
	array(
			"109",
			"Pneuma",
			"Adam Polselli",
			"http://www.adampolselli.com/",
	),
	array(
			"110",
			"Perfume de Gardenias",
			"Armando Sosa",
			"http://nolimit-studio.com/yosoysosa/",
	),
	array(
			"111",
			"Gr&#252;ener Entwurf",
			"Hannah F. Liesong",
			"http://www.liesong.de/",
	),
	array(
			"112",
			"Mountain Resort",
			"Jordi Romkema",
			"http://www.jor-on.com/",
	),
	array(
			"113",
			"Switch On",
			"Michael Fasani",
			"#",
	),
	array(
			"114",
			"Salvage Yard",
			"Justin Peters",
			"http://www.vatoweb.com/",
	),
	array(
			"115",
			"Burnt Offering",
			"Jonny Blair",
			"http://www.jonnyblair.co.uk/",
	),
	array(
			"116",
			"Ragged",
			"Jose Florido",
			"http://www.avidos.net/blogold/",
	),
	array(
			"117",
			"Brushwood",
			"Katrin Zieger",
			"#",
	),
	array(
			"118",
			"Some Leafs",
			"Michael Tupy",
			"http://www.t-2.at/",
	),
	array(
			"119",
			"Pleasant Day",
			"Kyle Jones",
			"http://www.justkyle.com/",
	),
	array(
			"120",
			"Medioevo",
			"Emiliano Pennisi",
			"http://www.peamarte.it/02/03.html",
	),
	array(
			"121",
			"60&#8217;s Lifestyle",
			"Emiliano Pennisi",
			"http://www.peamarte.it/02/03.html",
	),
	array(
			"122",
			"Centerfold",
			"John Oxton",
			"#",
	),
	array(
			"123",
			"Skyroots",
			"Axel Hebenstreit",
			"http://www.sonnenvogel.com/",
	),
	array(
			"124",
			"Teatime",
			"Michaela Maria Sampl",
			"http://members.chello.at/michaela.sampl/",
	),
	array(
			"125",
			"Beccah",
			"Chris Morrell",
			"http://www.cmorrell.com/",
	),
	array(
			"126",
			"C-Note",
			"Brian Williams",
			"http://www.ploughdeep.com/",
	),
	array(
			"127",
			"Vivacity",
			"Sofiane Toudji",
			"http://soso.2037.org/",
	),
	array(
			"128",
			"Dragen",
			"Matthew Buchanan",
			"http://www.cactuslab.com/",
	),

	// 129 removed for reasons lost in the mists of time

	array(
			"130",
			"Pseudo Sahara",
			"John Barrick",
			"http://www.waycoolwebdesign.com/",
	),
	array(
			"131",
			"Type Thing",
			"Michal Mokrzycki",
			"#",
	),


);

?>