	<?
	
	$filename = array(
			// 108 removed for copyright violation
			// 129 removed for some reason I no longer remember 
			// 183 removed for being horribly broken
	);
	
	$styleName = array(
			1 => "tranquille",
	
			"Golden Cut",
			"Invasion of the Body Switchers",
			"Pixelisation",
			"Verdure",
			"Paravion",
			"Urban",
			"Attitude",
			"Museum",
			"Uncultivated",
			"By The Pier",
			"Contempo Finery",
			"Subway Dream",
			"Moss",
			"Butterfly Effect",
			"November",
			"Table Layout Assassination!",
			"Bugs",
			"a Simple Sunrise",
			"Berry Flavour",
			"Daruma",
			"Zenfandel",
			"Angelus",
			"Like the Sea",
			"Chien",
			"Red Paper",
			"Obsequience",
			"Hoops - Tournament Edition",
			"Hengarden",
			"Greece Remembrance",
			"Love Is In The Air",
			"Shaolin Yokobue",
			"blackcomb*75",
			"Red Stars",
			"Simple",
			"Business Style",
			"Kelmscott",
			"Zen City Morning",
			"Pinups",
			"Vin Rouge",
			"Vertigo",
			"Pretty in Pink",
			"45 RPM",
			"Peace Of Mind",
			"Manhattan Edition",
			"Faded Flowers",
			"Wilderness",
			"Organica Creativa",
			"Mozart",
			"Lonely Flower",
			"The Diary",
			"LuGoZee",
			"Leggo My Ego",
			"Dark Rose",
			"Dazzling Beauty",
			"Elegance in Simplicity",
			"Floral Touch",
			"The Original",
			"CSS ZEN ARMY",
			"Icicle Outback",
			"Lily Pond",
			"Retro Theater",
			"Tiny Blue",
			"Withering Beauty",
			"spring360",
			"A Walk in the Garden",
			"Kyoto Forest",
			"Sakura",
			"CSS Co., Ltd.",
			"Oceanscape",
			"Orchid Beauty",
			"Make &#8217;em Proud",
			"Under the Sea!",
	);
	
	$styleURL = array(
			1 => "http://www.mezzoblue.com/",
	
			"http://www.pixy.cz/",
			"http://www.stuffandnonsense.co.uk/",
			"http://yuanqing.blogspot.com/",
			"http://yuanqing.blogspot.com/",
			"http://www.peamarte.it/01/metro.html",
			"http://www.learnnewmedia.ca/",
			"#",
			"http://www.info.fundp.ac.be/~sma/",
			"http://www.mariocarboni.com/",
			"http://peter.rock.per.sg/",
			"http://www.intersmash.com/",
			"http://www.nuevostudio.com/",
			"http://www.manisheriar.com/",
			"http://www.sitemaker.us/",
			"http://www.pixelpusher.biz/",
			"http://web.burza.hr/",
			"http://www.captainserious.co.uk/",
			"http://www.couchfort.net/",
			"http://www.honeyjazz.net/",
			"http://www.stuartandpetra.com/",
			"http://www.c82.net/",
			"http://www.wortahn.com/",
			"http://www.redrotate.de/",
			"http://www.pixul.net/",
			"http://www.couchfort.net/",
			"http://www.piercegleeson.com/",
			"http://www.pixelflexmedia.com/",
			"http://www.khmerang.com/",
			"http://www.kaligrafy.com/",
			"http://www.april-design.de/",
			"http://www.emaginacion.com.ar/hacks/",
			"http://www.carichner.com/",
			"http://www.1988online.net/",
			"http://www.shawnchin.net/",
			"http://www.klavina.com/",
			"http://www.cdevision.com/",
			"http://www.reh3.com/",
			"http://www.peamarte.it/02/03.html",
			"http://www.bopp-medien.de/",
			"http://www.digitalink.it/",
			"http://www.jor-on.com/",
			"http://www.ivfx.com/",
			"http://www.carlosvarela.net",
			"http://www.theom3ga.tk",
			"http://www.ManiSheriar.com",
			"http://www.idizyn.com/blog",
			"http://www.criaturacreativa.com",
			"http://www.geocities.com/andrew_brundle2003",
			"http://www.ribic.org/",
			"http://eye.loveline.ru",
			"http://www.accxs.net",
			"http://www.gr0w.com",
			"http://www.rosefu.net/",
			"http://blog.denysri.com/",
			"http://www.manisheriar.com/blog/",
			"http://www.jahmasta.com",
			"http://www.bluejam.com",
			"http://www.niceguy.com",
			"http://www.timovirtanen.com/",
			"http://tulips4rose.com",
			"http://space-sheeps.info/",
			"http://www.timovirtanen.com/",
			"http://www.wduffy.co.uk/",
			"http://www.medialab360.com",
			"http://users.skynet.be/bk316398/temp.html",
			"http://rpmdesignfactory.com/",
			"http://www.re-bloom.com/",
			"http://www.benklemm.de/",
			"http://www.pixel-house.com.au/",
			"http://www.kevinaddison.com/",
			"http://skybased.com/",
			"http://www.ericstoltz.com/",
	);
	
	$styleCreator = array(
			1 => "Dave Shea",
	
			"Petr Stanicek",
			"Andy Clarke",
			"Lim Yuan Qing",
			"Lim Yuan Qing",
			"Emiliano Pennisi",
			"Matt Kim &amp; Nicole",
			"Stephane Moens",
			"Samuel Marin",
			"Mario Carboni",
			"Peter Ong",
			"Ro London",
			"Pablo Caro",
			"Mani Sheriar",
			"Kevin Linkous",
			"Alen Grakalic",
			"Marko Krsul &amp; Marko Dugonjic",
			"Zohar Arad",
			"Rob Soule",
			"Maren Becker",
			"Stuart Cruickshank",
			"Nicholas Rougeux",
			"Vladimir Lukic",
			"Lars Daum",
			"Alex Miller",
			"Rob Soule",
			"Pierce Gleeson",
			"David Marshall Jr.",
			"Mr. Khmerang",
			"Pierre-Leo Bourbonnais",
			"Nele Goetz",
			"Javier Cabrera",
			"Bryan Carichner",
			"Shafiq Rizwan",
			"Shawn Chin",
			"Gunta Klavina",
			"Bronwen Hodgkinson",
			"Ray Henry",
			"Emiliano Pennisi",
			"Thorsten Bopp",
			"Antonio Cella",
			"Jordi Romkema",
			"Thomas Michaud",
			"Carlos Varela",
			"Jos&#233; Tom&#225;s Tocino Garc&#237;a",
			"Mani Sheriar",
			"Aadesh Mistry",
			"Eduardo Cesario",
			"Andrew Brundle",
			"Mitja Ribic",
			"Alexander Shabuniewicz",
			"Viallon Pierre-Antoine",
			"Jon Tan",
			"Rose Fu",
			"Deny Sri Supriyono",
			"Mani Sheriar",
			"Jadas Jimmy",
			"Joachim Shotter",
			"Carl Desmond",
			"Timo Virtanen",
			"Rose Thorogood",
			"Eric Rog&#233;",
			"Timo Virtanen",
			"William Duffy",
			"Rene Hornig",
			"Simon Van Hauwermeiren",
			"John Politowski",
			"Tatsuya Uchida",
			"Benjamin Klemm",
			"Justin Gray",
			"Kevin Addison",
			"Michael McAghon and Scotty Reifsnyder",
			"Eric Stoltz",
	);
	
	
	?>