<?

// Design master list
$designList = array(
	array(
			"001",
			"tranquille",
			"Dave Shea",
			"http://www.mezzoblue.com/",
	),
	array(
			"002",
			"Salmon Cream Cheese",
			"Dave Shea"	,
			"http://www.mezzoblue.com/",
	),
	array(
			"003",
			"Stormweather",
			"Dave Shea",
			"http://www.mezzoblue.com/",
	),
	array(
			"004",
			"arch4.20",
			"Dave Shea",
			"http://www.mezzoblue.com/",
	),
	array(
			"005",
			"Blood Lust",
			"Dave Shea",
			"http://www.mezzoblue.com/",
	),
	array(
			"006",
			"Wicked Grove",
			"D. Keith Robinson",
			"http://www.dkeithrobinson.com/",
	),
	array(
			"007",
			"deep thoughts",
			"Jason Estes",
			"#",
	),
	array(
			"008",
			"RPM",
			"Bruno Cunha",
			"#",
	),
	array(
			"009",
			"Dead or Alive",
			"Michael Pick",
			"http://www.mikepick.com/",
	),
	array(
			"010",
			"A Garden Apart",
			"Dan Cederholm",
			"http://www.simplebits.com/",
	),
	array(
			"011",
			"meliorism",
			"Brett J. Gilbert",
			"#",
	),
	array(
			"012",
			"TechnOhm",
			"Josh Ambrutis",
			"#",
	),
	array(
			"013",
			"Coastal Breeze",
			"Dave Shea",
			"http://www.mezzoblue.com/",
	),
	array(
			"014",
			"Samuraai",
			"Minz Meyer",
			"http://www.minzweb.de/",
	),
	array(
			"015",
			"Boddhidarma",
			"Michael Angeles",
			"http://www.urlgreyhot.com/",
	),
	array(
			"016",
			"The Garden Beneath",
			"Minz Meyer",
			"http://www.minzweb.de/",
	),
	array(
			"017",
			"Golden Mean",
			"Douglas Bowman",
			"http://www.stopdesign.com/",
	),
	array(
			"018",
			"Wrapped in Burlap",
			"John Simons",
			"http://www.royalbarrel.com/",
	),
	array(
			"019",
			"What Lies Beneath",
			"Michael Pick",
			"http://www.mikepick.com/",
	),
	array(
			"020",
			"Friendly Beaches",
			"Sophie G",
			"http://www.sophie-g.net/",
	),
	array(
			"021",
			"Calm &amp; Smooth",
			"Cornelia Lange",
			"http://www.clkm.de/",
	),
	array(
			"022",
			"viridity",
			"Laura MacArthur",
			"#",
	),
	array(
			"023",
			"fleur de l&#8217;avant-garde",
			"Michael Switzer",
			"#",
	),
	array(
			"024",
			"Not So Minimal",
			"Dan Rubin",
			"http://www.superfluousbanter.org/",
	),
	array(
			"025",
			"mnemonic",
			"Dave Shea",
			"http://www.mezzoblue.com/",
	),
	array(
			"026",
			"Zunflower",
			"Radu Darvas",
			"http://www.cssgatto.com/",
	),
	array(
			"027",
			"Gothica",
			"Patrick H. Lauke",
			"http://www.splintered.co.uk/",
	),
	array(
			"028",
			"Atlantis",
			"Kevin Davis",
			"http://alazanto.org/",
	),
	array(
			"029",
			"Backyard",
			"Ray Henry",
			"http://www.reh3.com/",
	),
	array(
			"030",
			"Entomology",
			"Jon Hicks",
			"http://exp.hicksdesign.co.uk/",
	),
	array(
			"031",
			"Hedges",
			"Kev Mears",
			"http://www.mearso.com/",
	),
	array(
			"032",
			"Crab Apple",
			"Jai Brinkofski",
			"#",
	),
	array(
			"033",
			"Fleur-de-lys",
			"Claire Campbell",
			"#",
	),
	array(
			"034",
			"zengrounds",
			"Andrea Piernock",
			"http://www.snooble.com/",
	),
	array(
			"035",
			"Release One",
			"Didier Hilhorst",
			"http://www.nundroo.com/",
	),
	array(
			"036",
			"White Lily",
			"Jens Kristensen",
			"http://j-k.com/",
	),
	array(
			"037",
			"pr&#234;t-&#225;-porter",
			"Minz Meyer",
			"http://www.minzweb.de/",
	),
	array(
			"038",
			"Creepy Crawly",
			"Luke Redpath",
			"",
	),
	array(
			"039",
			"Erratic Blue",
			"Ian Main",
			"#",
	),
	array(
			"040",
			"The Question Why",
			"Diane Clayton",
			"http://www.schisma.net/",
	),
	array(
			"041",
			"door to my garden",
			"Patrick H. Lauke",
			"http://www.splintered.co.uk/",
	),
	array(
			"042",
			"Stone Washed",
			"Andrew Hayward",
			"http://www.mooncalf.me.uk/",
	),
	array(
			"043",
			"Burning",
			"Kevin &#038; Ethel Davis",
			"http://etheldavisgallery.com/",
	),
	array(
			"044",
			"si6",
			"Shaun Inman",
			"http://www.shauninman.com/",
	),
	array(
			"045",
			"I Dream in Colour",
			"Jeff Bilen",
			"http://www.scribblersclub.com/",
	),
	array(
			"046",
			"sub:lime",
			"Andy Budd",
			"http://www.andybudd.com/",
	),
	array(
			"047",
			"dusk",
			"Jon Hicks",
			"http://exp.hicksdesign.co.uk/",
	),	
	array(
			"048",
			"HoriZental",
			"Cl&#233;ment &#8216;fastclemmy&#8217; Hardouin",
			"http://www.fastclemmy.com/",
	),	
	array(
			"049",
			"Buddha",
			"Daniel Leroux",
			"#",
	),	
	array(
			"050",
			"First Summary",
			"Cornelia Lange",
			"http://www.clkm.de/",
	),	
	array(
			"051",
			"Commercial Drive",
			"Wendy Foster",
			"#",
	),	
	array(
			"052",
			"Postage Paid",
			"Mike Stenhouse",
			"http://www.donotremove.co.uk/",
	),
	array(
			"053",
			"Self-Growth",
			"Ray Henry",
			"http://www.reh3.com/",
	),
	array(
			"054",
			"Gecko&#8217;s Eye",
			"Sandra Greco",
			"http://www.magritte.it/",
	),
	array(
			"055",
			"zenlightenment",
			"Lance Leonard",
			"http://www.solarfrog.com/",
	),
	array(
			"056",
			"Elevation",
			"Nigel Goodfellow",
			"http://www.beforethedog.com/",
	),
	array(
			"057",
			"This is Cereal",
			"Shaun Inman",
			"http://www.shauninman.com/",
	),
	array(
			"058",
			"Radio Zen",
			"Marc LA van den Heuvel",
			"http://www.mlavdh.nl/",
	),
	array(
			"059",
			"Dune Temple",
			"Greg Reimer",
			"http://www.drpeterjones.com/",
	),
	array(
			"060",
			"Extreme Limits",
			"Richard Chatfield",
			"#",
	),
	array(
			"061",
			"Sky",
			"Stefan Petre",
			"http://www.eyecon.ro/",
	),
	array(
			"062",
			"Gemination",
			"Egor Kloos",
			"http://www.dutchcelt.nl/",
	),
	array(
			"063",
			"Elastic Lawn",
			"Patrick Grifiths",
			"http://htmldog.com/ptg/",
	),
	array(
			"064",
			"Night Drive",
			"Dave Shea",
			"http://www.mezzoblue.com/",
	),
	array(
			"065",
			"New Groove",
			"Martin Neumann",
			"http://www.rushmedia.de/",
	),
	array(
			"066",
			"Focus &amp; Shoot",
			"Colectivo YTW",
			"#",
	),
	array(
			"067",
			"A Silent Strength",
			"Ray Henry",
			"http://www.reh3.com/",
	),
	array(
			"068",
			"Ballade",
			"Charlotte Lambert",
			"#",
	),
	array(
			"069",
			"Bonsai Sky",
			"Mike Davidson",
			"http://www.mikeindustries.com/",
	),
	array(
			"070",
			"CS(S) Monk",
			"Cedric Savarese",
			"http://www.4213miles.com/",
	),
	array(
			"071",
			"Garden Party",
			"Bobby van der Sluis",
			"http://www.bobbyvandersluis.com/",
	),
	array(
			"072",
			"Outburst",
			"Chris Vincent",
			"#",
	),
	array(
			"073",
			"Emmakade",
			"Alexander Christiaan Jacob (ACJ)",
			"http://acjs.net/",
	),
	array(
			"074",
			"Egyptian Dawn",
			"James Abbott",
			"mailto:jambot@hotmail.com",
	),
	array(
			"075",
			"Lost HighWay",
			"Julien Roumagnac",
			"http://www.j-roumagnac.net/",
	),
	array(
			"076",
			"Lotus",
			"Chika",
			"http://deja.boo.jp/japdsn/",
	),
	array(
			"077",
			"Hop",
			"Guillaume Lahalle",
			"#",
	),
	array(
			"078",
			"Muto Verde",
			"Alex Taylor",
			"#",
	),
	array(
			"079",
			"Green Tea",
			"Amy Rae Som",
			"http://www.avisualmind.com/",
	),
	array(
			"080",
			"Zen Pool",
			"Clinton Barth",
			"http://www.516media.com/",
	),



);


?>