<?

$filename = array(
		// 108 removed for copyright violation
		// 129 removed for some reason I no longer remember 
		// 183 removed for being horribly broken
);

$styleName = array(
		1 => "tranquille",

		"Creepy Crawly",
		"Erratic Blue",
		"The Question Why",
		"door to my garden",
		"Stone Washed",
		"Burning",
		"si6",
		"I Dream in Colour",
		"sub:lime",
		"dusk",
		"HoriZental",
		"Buddha",
		"First Summary",
		"Commercial Drive",
		"Postage Paid",
		"Self-Growth",
		"Gecko&#8217;s Eye",
		"zenlightenment",
		"Elevation",
		"This is Cereal",
		"Radio Zen",
		"Dune Temple",
		"Extreme Limits",
		"Sky",
		"Gemination",
		"Elastic Lawn",
		"Night Drive",
		"New Groove",
		"Focus &amp; Shoot",
		"A Silent Strength",
		"Ballade",
		"Bonsai Sky",
		"CS(S) Monk",
		"Garden Party",
		"Outburst",
		"Emmakade",
		"Egyptian Dawn",
		"Lost HighWay",
		"Lotus",
		"Hop",
		"Muto Verde",
		"Green Tea",
		"Zen Pool",
		"seashore",
		"Miracle Cure",
		"Springtime",
		"Start Listening!",
		"Oceans Apart",
		"RedFrog",
		"Maya",
		"Tulipe",
		"Dark Industrial",
		"Open Window",
		"webZine",
		"Port of Call",
		"South of the Border",
		"Deco",
		"Corporate ZenWorks",
		"Japanese Garden",
		"No Frontiers!",
		"Edo and Tokyo",
		"Wiggles the Wonderworm",
		"15 Petals",
		"Punkass",
		"Revolution!",
		"Odyssey",
		"Invitation",
		"Austrian&#8217;s Darker Side",
		"Mediterranean",
		"Defiance",
		"Pneuma",
		"Perfume de Gardenias",
		"Gr&#252;ener Entwurf",
		"Mountain Resort",
		"Switch On",
		"Salvage Yard",
		"Burnt Offering",
		"Ragged",
		"Brushwood",
		"Some Leafs",
		"Pleasant Day",
		"Medioevo",
		"60&#8217;s Lifestyle",
		"Centerfold",
		"Skyroots",
		"Teatime",
		"Beccah",
		"C-Note",
		"Vivacity",
		"Dragen",
		"Pseudo Sahara",
		"Type Thing",
		"Bonsai",
		"OrderedZen",
		"El Collar de Tomas",
		"contemporary nouveau",
		"The Final Ending",
		"DJ Style",
		"Cube Garden",
		"Neat &amp; Tidy",
		"The Hall",
		"Golden Cut",
		"Invasion of the Body Switchers",
		"Pixelisation",
		"Verdure",
		"Paravion",
		"Urban",
		"Attitude",
		"Museum",
		"Uncultivated",
		"By The Pier",
		"Contempo Finery",
		"Subway Dream",
		"Moss",
		"Butterfly Effect",
		"November",
		"Table Layout Assassination!",
		"Bugs",
		"a Simple Sunrise",
		"Berry Flavour",
		"Daruma",
		"Zenfandel",
		"Angelus",
		"Like the Sea",
		"Chien",
		"Red Paper",
		"Obsequience",
		"Hoops - Tournament Edition",
		"Hengarden",
		"Greece Remembrance",
		"Love Is In The Air",
		"Shaolin Yokobue",
		"blackcomb*75",
		"Red Stars",
		"Simple",
		"Business Style",
		"Kelmscott",
		"Zen City Morning",
		"Pinups",
		"Vin Rouge",
		"Vertigo",
		"Pretty in Pink",
		"45 RPM",
		"Peace Of Mind",
		"Manhattan Edition",
		"Faded Flowers",
		"Wilderness",
		"Organica Creativa",
		"Mozart",
		"Lonely Flower",
		"The Diary",
		"LuGoZee",
		"Leggo My Ego",
		"Dark Rose",
		"Dazzling Beauty",
		"Elegance in Simplicity",
		"Floral Touch",
		"The Original",
		"CSS ZEN ARMY",
		"Icicle Outback",
		"Lily Pond",
		"Retro Theater",
		"Tiny Blue",
		"Withering Beauty",
		"spring360",
		"A Walk in the Garden",
		"Kyoto Forest",
		"Sakura",
		"CSS Co., Ltd.",
		"Oceanscape",
		"Orchid Beauty",
		"Make &#8217;em Proud",
		"Under the Sea!",
);

$styleURL = array(
		1 => "http://www.mezzoblue.com/",

		"http://www.sonicdeath.co.uk/",
		"http://www.e-lusion.com/",
		"http://www.schisma.net/",
		"http://www.splintered.co.uk/",
		"http://www.mooncalf.me.uk/",
		"http://etheldavisgallery.com/",
		"http://www.shauninman.com/",
		"http://www.scribblersclub.com/",
		"http://www.andybudd.com/blog/",
		"http://exp.hicksdesign.co.uk/",
		"http://www.fastclemmy.com/",
		"http://www.nwebit.com/",
		"http://www.clkm.de/",
		"http://www.transgression.ca/",
		"http://www.donotremove.co.uk/",
		"http://www.reh3.com/",
		"http://www.magritte.it/",
		"http://www.solarfrog.com/",
		"http://www.beforethedog.com/",
		"http://www.shauninman.com/",
		"http://www.mlavdh.nl/",
		"http://www.drpeterjones.com/",
		"http://www.engagecommerce.com/",
		"http://www.eyecon.ro/",
		"http://www.dutchcelt.nl/",
		"http://htmldog.com/ptg/",
		"http://www.mezzoblue.com/",
		"http://www.rushmedia.de/",
		"#",
		"http://www.reh3.com/",
		"http://charlotte.flibuste.net/",
		"http://www.mdavidson.com/",
		"http://www.4213miles.com/",
		"http://www.bobbyvandersluis.com/",
		"http://dris.webhop.org/",
		"http://acjs.net/",
		"mailto:jambot@hotmail.com",
		"http://www.j-roumagnac.net/",
		"http://deja.boo.jp/japdsn/",
		"http://www.kh0d.com/",
		"http://www.alextaylor.org/",
		"http://www.avisualmind.com/",
		"http://www.516media.com/",
		"http://www.sightdesign.de/",
		"http://www.make-believe.org/",
		"http://www.calcium.ro/",
		"http://hiptobeasquare.com/",
		"http://www.justwatchthesky.com/",
		"http://www.willenberg.biz/",
		"http://www.willenberg.biz/",
		"http://www.arkitrave.com/log",
		"http://www.reh3.com/",
		"http://www.reh3.com/",
		"http://www.20cent.net/",
		"http://vcdesignconcept.com/",
		"http://www.dotcat.org/",
		"http://www.marctrudel.com/",
		"http://www.dejoha.com/",
		"http://www.jugglinglife.org/",
		"http://hyperreal.info/bhang/",
		"http://www.coutworks.com/",
		"http://www.make-believe.org/",
		"http://www.meyerweb.com/",
		"http://www.mikhel.com/",
		"http://www.monc.se/",
		"http://www.liquidarch.com/",
		"http://www.bradleyboy.com/",
		"http://www.grassegger.at/",
		"http://www.basseq.com/",
		"http://www.ehlydesign.com/",
		"http://www.adampolselli.com/",
		"http://nolimit-studio.com/yosoysosa/",
		"http://www.liesong.de/",
		"http://www.jor-on.com/",
		"http://www.michaelfasani.com/",
		"http://www.vatoweb.com/",
		"http://www.jonnyblair.co.uk/",
		"http://www.avidos.net/blogold/",
		"http://www.crea-z.de/",
		"http://www.t-2.at/",
		"http://www.justkyle.com/",
		"http://www.peamarte.it/02/03.html",
		"http://www.peamarte.it/02/03.html",
		"http://www.joshuaink.com/",
		"http://www.sonnenvogel.com/",
		"http://members.chello.at/michaela.sampl/",
		"http://www.cmorrell.com/",
		"http://www.ploughdeep.com/",
		"http://soso.2037.org/",
		"http://www.cactuslab.com/",
		"http://www.waycoolwebdesign.com/",
		"http://nf.hyperreal.info/",
		"http://martin.plazotta.at/",
		"http://www.orderedlist.com/",
		"http://www.mqstudio.com/",
		"http://www.monc.se/",
		"http://www.reh3.com/",
		"http://ilhasol.com/bastidores.asp",
		"http://www.804case.com/",
		"http://www.designerstalk.com/",
		"http://www.thoughtanomalies.com/",
		"http://www.pixy.cz/",
		"http://www.stuffandnonsense.co.uk/",
		"http://yuanqing.blogspot.com/",
		"http://yuanqing.blogspot.com/",
		"http://www.peamarte.it/01/metro.html",
		"http://www.learnnewmedia.ca/",
		"#",
		"http://www.info.fundp.ac.be/~sma/",
		"http://www.mariocarboni.com/",
		"http://peter.rock.per.sg/",
		"http://www.intersmash.com/",
		"http://www.nuevostudio.com/",
		"http://www.manisheriar.com/",
		"http://www.sitemaker.us/",
		"http://www.pixelpusher.biz/",
		"http://web.burza.hr/",
		"http://www.captainserious.co.uk/",
		"http://www.couchfort.net/",
		"http://www.honeyjazz.net/",
		"http://www.stuartandpetra.com/",
		"http://www.c82.net/",
		"http://www.wortahn.com/",
		"http://www.redrotate.de/",
		"http://www.pixul.net/",
		"http://www.couchfort.net/",
		"http://www.piercegleeson.com/",
		"http://www.pixelflexmedia.com/",
		"http://www.khmerang.com/",
		"http://www.kaligrafy.com/",
		"http://www.april-design.de/",
		"http://www.emaginacion.com.ar/hacks/",
		"http://www.carichner.com/",
		"http://www.1988online.net/",
		"http://www.shawnchin.net/",
		"http://www.klavina.com/",
		"http://www.cdevision.com/",
		"http://www.reh3.com/",
		"http://www.peamarte.it/02/03.html",
		"http://www.bopp-medien.de/",
		"http://www.digitalink.it/",
		"http://www.jor-on.com/",
		"http://www.ivfx.com/",
		"http://www.carlosvarela.net",
		"http://www.theom3ga.tk",
		"http://www.ManiSheriar.com",
		"http://www.idizyn.com/blog",
		"http://www.criaturacreativa.com",
		"http://www.geocities.com/andrew_brundle2003",
		"http://www.ribic.org/",
		"http://eye.loveline.ru",
		"http://www.accxs.net",
		"http://www.gr0w.com",
		"http://www.rosefu.net/",
		"http://blog.denysri.com/",
		"http://www.manisheriar.com/blog/",
		"http://www.jahmasta.com",
		"http://www.bluejam.com",
		"http://www.niceguy.com",
		"http://www.timovirtanen.com/",
		"http://tulips4rose.com",
		"http://space-sheeps.info/",
		"http://www.timovirtanen.com/",
		"http://www.wduffy.co.uk/",
		"http://www.medialab360.com",
		"http://users.skynet.be/bk316398/temp.html",
		"http://rpmdesignfactory.com/",
		"http://www.re-bloom.com/",
		"http://www.benklemm.de/",
		"http://www.pixel-house.com.au/",
		"http://www.kevinaddison.com/",
		"http://skybased.com/",
		"http://www.ericstoltz.com/",
);

$styleCreator = array(
		1 => "Dave Shea",

		"Luke Redpath",
		"Ian Main",
		"Diane Clayton",
		"Patrick H. Lauke",
		"Andrew Hayward",
		"Kevin &#038; Ethel Davis",
		"Shaun Inman",
		"Jeff Bilen",
		"Andy Budd",
		"Jon Hicks",
		"Cl&#233;ment &#8216;fastclemmy&#8217; Hardouin",
		"Daniel Leroux",
		"Cornelia Lange",
		"Wendy Foster",
		"Mike Stenhouse",
		"Ray Henry",
		"Sandra Greco",
		"Lance Leonard",
		"Nigel Goodfellow",
		"Shaun Inman",
		"Marc LA van den Heuvel",
		"Greg Reimer",
		"Richard Chatfield",
		"Stefan Petre",
		"Egor Kloos",
		"Patrick Grifiths",
		"Dave Shea",
		"Martin Neumann",
		"Colectivo YTW",
		"Ray Henry",
		"Charlotte Lambert",
		"Mike Davidson",
		"Cedric Savarese",
		"Bobby van der Sluis",
		"Chris Vincent",
		"Alexander Christiaan Jacob (ACJ)",
		"James Abbott",
		"Julien Roumagnac",
		"Chika",
		"Guillaume Lahalle",
		"Alex Taylor",
		"Amy Rae Som",
		"Clinton Barth",
		"Christine Kirchmeier",
		"Joseph Pearson",
		"Bo&eacute;r Attila",
		"Liz Lubowitz",
		"Ryan Sims",
		"Bernd Willenberg",
		"Bernd Willenberg",
		"Eric Shepherd",
		"Ray Henry",
		"Ray Henry",
		"Vincent Valentin",
		"Jessica Dunn",
		"Rob Shields",
		"Marc Trudel",
		"Derek Hansen",
		"Masanori Kawachi",
		"Michal Mokrzycki",
		"Daisuke Sato",
		"Joseph Pearson",
		"Eric Meyer &amp; Dave Shea",
		"Mikhel Proulx",
		"David Hellsing",
		"Terrence Conley",
		"Brad Daily",
		"Rene Grassegger",
		"John Whittet",
		"James Ehly",
		"Adam Polselli",
		"Armando Sosa",
		"Hannah F. Liesong",
		"Jordi Romkema",
		"Michael Fasani",
		"Justin Peters",
		"Jonny Blair",
		"Jose Florido",
		"Katrin Zieger",
		"Michael Tupy",
		"Kyle Jones",
		"Emiliano Pennisi",
		"Emiliano Pennisi",
		"John Oxton",
		"Axel Hebenstreit",
		"Michaela Maria Sampl",
		"Chris Morrell",
		"Brian Williams",
		"Sofiane Toudji",
		"Matthew Buchanan",
		"John Barrick",
		"Michal Mokrzycki",
		"Martin Plazotta",
		"Steve Smith",
		"Maria Stultz",
		"David Hellsing",
		"Ray Henry",
		"Ramon Bispo",
		"Masanori Kawachi",
		"Oli Dale",
		"Michael Simmons",
		"Petr Stanicek",
		"Andy Clarke",
		"Lim Yuan Qing",
		"Lim Yuan Qing",
		"Emiliano Pennisi",
		"Matt Kim &amp; Nicole",
		"Stephane Moens",
		"Samuel Marin",
		"Mario Carboni",
		"Peter Ong",
		"Ro London",
		"Pablo Caro",
		"Mani Sheriar",
		"Kevin Linkous",
		"Alen Grakalic",
		"Marko Krsul &amp; Marko Dugonjic",
		"Zohar Arad",
		"Rob Soule",
		"Maren Becker",
		"Stuart Cruickshank",
		"Nicholas Rougeux",
		"Vladimir Lukic",
		"Lars Daum",
		"Alex Miller",
		"Rob Soule",
		"Pierce Gleeson",
		"David Marshall Jr.",
		"Mr. Khmerang",
		"Pierre-Leo Bourbonnais",
		"Nele Goetz",
		"Javier Cabrera",
		"Bryan Carichner",
		"Shafiq Rizwan",
		"Shawn Chin",
		"Gunta Klavina",
		"Bronwen Hodgkinson",
		"Ray Henry",
		"Emiliano Pennisi",
		"Thorsten Bopp",
		"Antonio Cella",
		"Jordi Romkema",
		"Thomas Michaud",
		"Carlos Varela",
		"Jos&#233; Tom&#225;s Tocino Garc&#237;a",
		"Mani Sheriar",
		"Aadesh Mistry",
		"Eduardo Cesario",
		"Andrew Brundle",
		"Mitja Ribic",
		"Alexander Shabuniewicz",
		"Viallon Pierre-Antoine",
		"Jon Tan",
		"Rose Fu",
		"Deny Sri Supriyono",
		"Mani Sheriar",
		"Jadas Jimmy",
		"Joachim Shotter",
		"Carl Desmond",
		"Timo Virtanen",
		"Rose Thorogood",
		"Eric Rog&#233;",
		"Timo Virtanen",
		"William Duffy",
		"Rene Hornig",
		"Simon Van Hauwermeiren",
		"John Politowski",
		"Tatsuya Uchida",
		"Benjamin Klemm",
		"Justin Gray",
		"Kevin Addison",
		"Michael McAghon and Scotty Reifsnyder",
		"Eric Stoltz",
);


?>